services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8181:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  flink-jobmanager:
    build:
      context: .
      dockerfile: Dockerfile.flink
    image: custom-flink:1.20.0
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    volumes:
      - /Users/evro/non_iCloud_files/Code/python/soccer_data_project/src:/flink/src
      - /Users/evro/non_iCloud_files/Code/python/soccer_data_project/config:/flink/config
      - /Users/evro/non_iCloud_files/Code/python/soccer_data_project/jars/flink-sql-connector-kafka-3.4.0-1.20.jar:/opt/flink/lib/flink-sql-connector-kafka-3.4.0-1.20.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
    command: jobmanager

  flink-taskmanager:
    build:
      context: .
      dockerfile: Dockerfile.flink
    image: custom-flink:1.20.0
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    volumes:
      - /Users/evro/non_iCloud_files/Code/python/soccer_data_project/src:/flink/src
      - /Users/evro/non_iCloud_files/Code/python/soccer_data_project/config:/flink/config
      - /Users/evro/non_iCloud_files/Code/python/soccer_data_project/jars/flink-sql-connector-kafka-3.4.0-1.20.jar:/opt/flink/lib/flink-sql-connector-kafka-3.4.0-1.20.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        env.java.opts=-Djava.library.path=/usr/lib -Djdk.module.add-exports=jdk.compiler=com.sun.tools.javac.code
    command: taskmanager
